#include "union-find/QuickFind.hpp"
#include "union-find/QuickUnion.hpp"
#include "union-find/QuickUnion_weighted.hpp"
#include "union-find/QuickUnion_pathComp.hpp"
#include "union-find/QuickUnion_weightedPathComp.hpp"
